apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: cicd-demo
type: Opaque
data:
  host: <DB_HOST_BASE64>
  port: NTQzMg==  # 5432
  username: cG9zdGdyZXM=  # postgres
  password: <DB_PASSWORD_BASE64>
  database: Y2ljZF9kZW1v  # cicd_demo
